import LayoutDashboard from "@/Components/LandingPage/LayoutDashboard";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <LayoutDashboard>{children}</LayoutDashboard>
        </main>
      </body>
    </html>
  );
}
